-- Foreign keys
ALTER TABLE organization ADD CONSTRAINT fk_organization_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant(tenant_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE organization ADD CONSTRAINT fk_organization_parent_id FOREIGN KEY (parent_id) REFERENCES organization(organization_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE app_user ADD CONSTRAINT fk_app_user_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant(tenant_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE app_user ADD CONSTRAINT fk_app_user_organization_id FOREIGN KEY (organization_id) REFERENCES organization(organization_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE role ADD CONSTRAINT fk_role_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant(tenant_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE user_role ADD CONSTRAINT fk_user_role_user_id FOREIGN KEY (user_id) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE user_role ADD CONSTRAINT fk_user_role_role_id FOREIGN KEY (role_id) REFERENCES role(role_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE user_role ADD CONSTRAINT fk_user_role_granted_by FOREIGN KEY (granted_by) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE user_session ADD CONSTRAINT fk_user_session_user_id FOREIGN KEY (user_id) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE plan ADD CONSTRAINT fk_plan_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant(tenant_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE plan ADD CONSTRAINT fk_plan_document_id FOREIGN KEY (document_id) REFERENCES document(document_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE plan ADD CONSTRAINT fk_plan_current_context_snapshot_id FOREIGN KEY (current_context_snapshot_id) REFERENCES plan_context_snapshot(context_snapshot_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE plan_context_draft ADD CONSTRAINT fk_plan_context_draft_plan_id FOREIGN KEY (plan_id) REFERENCES plan(plan_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE plan_context_draft ADD CONSTRAINT fk_plan_context_draft_updated_by FOREIGN KEY (updated_by) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE plan_context_snapshot ADD CONSTRAINT fk_plan_context_snapshot_plan_id FOREIGN KEY (plan_id) REFERENCES plan(plan_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE plan_context_snapshot ADD CONSTRAINT fk_plan_context_snapshot_supersedes_id FOREIGN KEY (supersedes_id) REFERENCES plan_context_snapshot(context_snapshot_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE plan_context_snapshot ADD CONSTRAINT fk_plan_context_snapshot_confirmed_by FOREIGN KEY (confirmed_by) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE toc_version ADD CONSTRAINT fk_toc_version_plan_id FOREIGN KEY (plan_id) REFERENCES plan(plan_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE toc_version ADD CONSTRAINT fk_toc_version_created_by FOREIGN KEY (created_by) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE toc_node ADD CONSTRAINT fk_toc_node_toc_version_id FOREIGN KEY (toc_version_id) REFERENCES toc_version(toc_version_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE generation_job ADD CONSTRAINT fk_generation_job_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant(tenant_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE job_event ADD CONSTRAINT fk_job_event_job_id FOREIGN KEY (job_id) REFERENCES generation_job(job_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE document ADD CONSTRAINT fk_document_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant(tenant_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE document ADD CONSTRAINT fk_document_source_file_id FOREIGN KEY (source_file_id) REFERENCES file_object(file_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE document ADD CONSTRAINT fk_document_current_revision_id FOREIGN KEY (current_revision_id) REFERENCES document_revision(revision_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE document_revision ADD CONSTRAINT fk_document_revision_document_id FOREIGN KEY (document_id) REFERENCES document(document_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE document_revision ADD CONSTRAINT fk_document_revision_parent_revision_id FOREIGN KEY (parent_revision_id) REFERENCES document_revision(revision_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE document_revision ADD CONSTRAINT fk_document_revision_created_by FOREIGN KEY (created_by) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE document_block ADD CONSTRAINT fk_document_block_revision_id FOREIGN KEY (revision_id) REFERENCES document_revision(revision_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE document_block ADD CONSTRAINT fk_document_block_parent_block_id FOREIGN KEY (parent_block_id) REFERENCES document_block(block_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE change_set ADD CONSTRAINT fk_change_set_document_id FOREIGN KEY (document_id) REFERENCES document(document_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE change_set ADD CONSTRAINT fk_change_set_base_revision_id FOREIGN KEY (base_revision_id) REFERENCES document_revision(revision_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE change_set ADD CONSTRAINT fk_change_set_result_revision_id FOREIGN KEY (result_revision_id) REFERENCES document_revision(revision_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE change_operation ADD CONSTRAINT fk_change_operation_change_set_id FOREIGN KEY (change_set_id) REFERENCES change_set(change_set_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE template_profile ADD CONSTRAINT fk_template_profile_document_id FOREIGN KEY (document_id) REFERENCES document(document_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE style_prototype ADD CONSTRAINT fk_style_prototype_template_profile_id FOREIGN KEY (template_profile_id) REFERENCES template_profile(template_profile_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE file_object ADD CONSTRAINT fk_file_object_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant(tenant_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE export_job ADD CONSTRAINT fk_export_job_document_id FOREIGN KEY (document_id) REFERENCES document(document_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE export_job ADD CONSTRAINT fk_export_job_revision_id FOREIGN KEY (revision_id) REFERENCES document_revision(revision_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE export_job ADD CONSTRAINT fk_export_job_requested_by FOREIGN KEY (requested_by) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE situation ADD CONSTRAINT fk_situation_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant(tenant_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE situation ADD CONSTRAINT fk_situation_current_snapshot_id FOREIGN KEY (current_snapshot_id) REFERENCES situation_snapshot(snapshot_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE situation ADD CONSTRAINT fk_situation_created_by FOREIGN KEY (created_by) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE situation_fact ADD CONSTRAINT fk_situation_fact_situation_id FOREIGN KEY (situation_id) REFERENCES situation(situation_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE situation_fact ADD CONSTRAINT fk_situation_fact_source_id FOREIGN KEY (source_id) REFERENCES fact_source(source_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE fact_conflict ADD CONSTRAINT fk_fact_conflict_situation_id FOREIGN KEY (situation_id) REFERENCES situation(situation_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE conflict_resolution ADD CONSTRAINT fk_conflict_resolution_conflict_id FOREIGN KEY (conflict_id) REFERENCES fact_conflict(conflict_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE conflict_resolution ADD CONSTRAINT fk_conflict_resolution_selected_fact_id FOREIGN KEY (selected_fact_id) REFERENCES situation_fact(fact_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE conflict_resolution ADD CONSTRAINT fk_conflict_resolution_resolved_by FOREIGN KEY (resolved_by) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE situation_snapshot ADD CONSTRAINT fk_situation_snapshot_situation_id FOREIGN KEY (situation_id) REFERENCES situation(situation_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE situation_snapshot ADD CONSTRAINT fk_situation_snapshot_supersedes_id FOREIGN KEY (supersedes_id) REFERENCES situation_snapshot(snapshot_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE situation_snapshot ADD CONSTRAINT fk_situation_snapshot_confirmed_by FOREIGN KEY (confirmed_by) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE provider_job ADD CONSTRAINT fk_provider_job_situation_id FOREIGN KEY (situation_id) REFERENCES situation(situation_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE knowledge_document ADD CONSTRAINT fk_knowledge_document_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant(tenant_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE knowledge_document ADD CONSTRAINT fk_knowledge_document_situation_id FOREIGN KEY (situation_id) REFERENCES situation(situation_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE knowledge_document ADD CONSTRAINT fk_knowledge_document_file_id FOREIGN KEY (file_id) REFERENCES file_object(file_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE evidence_set ADD CONSTRAINT fk_evidence_set_situation_id FOREIGN KEY (situation_id) REFERENCES situation(situation_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE evidence_set ADD CONSTRAINT fk_evidence_set_snapshot_id FOREIGN KEY (snapshot_id) REFERENCES situation_snapshot(snapshot_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE evidence_set ADD CONSTRAINT fk_evidence_set_created_by FOREIGN KEY (created_by) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE evidence_item ADD CONSTRAINT fk_evidence_item_evidence_set_id FOREIGN KEY (evidence_set_id) REFERENCES evidence_set(evidence_set_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE evidence_item ADD CONSTRAINT fk_evidence_item_knowledge_document_id FOREIGN KEY (knowledge_document_id) REFERENCES knowledge_document(knowledge_document_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sop ADD CONSTRAINT fk_sop_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant(tenant_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sop ADD CONSTRAINT fk_sop_situation_id FOREIGN KEY (situation_id) REFERENCES situation(situation_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sop ADD CONSTRAINT fk_sop_current_version_id FOREIGN KEY (current_version_id) REFERENCES sop_version(sop_version_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sop ADD CONSTRAINT fk_sop_created_by FOREIGN KEY (created_by) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sop_version ADD CONSTRAINT fk_sop_version_sop_id FOREIGN KEY (sop_id) REFERENCES sop(sop_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sop_version ADD CONSTRAINT fk_sop_version_source_evidence_set_id FOREIGN KEY (source_evidence_set_id) REFERENCES evidence_set(evidence_set_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sop_version ADD CONSTRAINT fk_sop_version_approved_by FOREIGN KEY (approved_by) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sop_node ADD CONSTRAINT fk_sop_node_sop_version_id FOREIGN KEY (sop_version_id) REFERENCES sop_version(sop_version_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sop_edge ADD CONSTRAINT fk_sop_edge_sop_version_id FOREIGN KEY (sop_version_id) REFERENCES sop_version(sop_version_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sop_edge ADD CONSTRAINT fk_sop_edge_from_node_id FOREIGN KEY (from_node_id) REFERENCES sop_node(node_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sop_edge ADD CONSTRAINT fk_sop_edge_to_node_id FOREIGN KEY (to_node_id) REFERENCES sop_node(node_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sop_validation ADD CONSTRAINT fk_sop_validation_sop_version_id FOREIGN KEY (sop_version_id) REFERENCES sop_version(sop_version_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sop_validation ADD CONSTRAINT fk_sop_validation_validated_by FOREIGN KEY (validated_by) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sop_run ADD CONSTRAINT fk_sop_run_sop_version_id FOREIGN KEY (sop_version_id) REFERENCES sop_version(sop_version_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sop_run ADD CONSTRAINT fk_sop_run_situation_id FOREIGN KEY (situation_id) REFERENCES situation(situation_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sop_run ADD CONSTRAINT fk_sop_run_snapshot_id FOREIGN KEY (snapshot_id) REFERENCES situation_snapshot(snapshot_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sop_run ADD CONSTRAINT fk_sop_run_started_by FOREIGN KEY (started_by) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE task ADD CONSTRAINT fk_task_run_id FOREIGN KEY (run_id) REFERENCES sop_run(run_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE task ADD CONSTRAINT fk_task_node_id FOREIGN KEY (node_id) REFERENCES sop_node(node_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE task ADD CONSTRAINT fk_task_assignee_user_id FOREIGN KEY (assignee_user_id) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE task ADD CONSTRAINT fk_task_assignee_org_id FOREIGN KEY (assignee_org_id) REFERENCES organization(organization_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE task_event ADD CONSTRAINT fk_task_event_task_id FOREIGN KEY (task_id) REFERENCES task(task_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE task_event ADD CONSTRAINT fk_task_event_actor_id FOREIGN KEY (actor_id) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE task_attachment ADD CONSTRAINT fk_task_attachment_task_id FOREIGN KEY (task_id) REFERENCES task(task_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE task_attachment ADD CONSTRAINT fk_task_attachment_file_id FOREIGN KEY (file_id) REFERENCES file_object(file_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE task_attachment ADD CONSTRAINT fk_task_attachment_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE dispatch ADD CONSTRAINT fk_dispatch_task_id FOREIGN KEY (task_id) REFERENCES task(task_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE dispatch ADD CONSTRAINT fk_dispatch_situation_id FOREIGN KEY (situation_id) REFERENCES situation(situation_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE dispatch ADD CONSTRAINT fk_dispatch_created_by FOREIGN KEY (created_by) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE dispatch_recipient ADD CONSTRAINT fk_dispatch_recipient_dispatch_id FOREIGN KEY (dispatch_id) REFERENCES dispatch(dispatch_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE dispatch_recipient ADD CONSTRAINT fk_dispatch_recipient_user_id FOREIGN KEY (user_id) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE dispatch_recipient ADD CONSTRAINT fk_dispatch_recipient_organization_id FOREIGN KEY (organization_id) REFERENCES organization(organization_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE execution_event ADD CONSTRAINT fk_execution_event_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant(tenant_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE execution_event ADD CONSTRAINT fk_execution_event_situation_id FOREIGN KEY (situation_id) REFERENCES situation(situation_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE execution_event ADD CONSTRAINT fk_execution_event_actor_id FOREIGN KEY (actor_id) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE execution_event ADD CONSTRAINT fk_execution_event_corrects_event_id FOREIGN KEY (corrects_event_id) REFERENCES execution_event(execution_event_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE outbox_message ADD CONSTRAINT fk_outbox_message_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant(tenant_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE outbox_attempt ADD CONSTRAINT fk_outbox_attempt_outbox_id FOREIGN KEY (outbox_id) REFERENCES outbox_message(outbox_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE journal ADD CONSTRAINT fk_journal_situation_id FOREIGN KEY (situation_id) REFERENCES situation(situation_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE journal ADD CONSTRAINT fk_journal_snapshot_id FOREIGN KEY (snapshot_id) REFERENCES situation_snapshot(snapshot_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE journal ADD CONSTRAINT fk_journal_document_id FOREIGN KEY (document_id) REFERENCES document(document_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE journal ADD CONSTRAINT fk_journal_created_by FOREIGN KEY (created_by) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE journal_projection_item ADD CONSTRAINT fk_journal_projection_item_journal_id FOREIGN KEY (journal_id) REFERENCES journal(journal_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE evaluation ADD CONSTRAINT fk_evaluation_situation_id FOREIGN KEY (situation_id) REFERENCES situation(situation_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE evaluation ADD CONSTRAINT fk_evaluation_created_by FOREIGN KEY (created_by) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE evaluation_score ADD CONSTRAINT fk_evaluation_score_evaluation_id FOREIGN KEY (evaluation_id) REFERENCES evaluation(evaluation_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE improvement_action ADD CONSTRAINT fk_improvement_action_evaluation_id FOREIGN KEY (evaluation_id) REFERENCES evaluation(evaluation_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE improvement_action ADD CONSTRAINT fk_improvement_action_owner_user_id FOREIGN KEY (owner_user_id) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE provider_config ADD CONSTRAINT fk_provider_config_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant(tenant_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE audit_log ADD CONSTRAINT fk_audit_log_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant(tenant_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE audit_log ADD CONSTRAINT fk_audit_log_actor_id FOREIGN KEY (actor_id) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE retention_policy ADD CONSTRAINT fk_retention_policy_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant(tenant_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE notification ADD CONSTRAINT fk_notification_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenant(tenant_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE notification ADD CONSTRAINT fk_notification_user_id FOREIGN KEY (user_id) REFERENCES app_user(user_id) DEFERRABLE INITIALLY DEFERRED;

-- High-value query indexes
CREATE INDEX IF NOT EXISTS ix_document_tenant_status_updated ON document(tenant_id, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS ix_plan_tenant_status_updated ON plan(tenant_id, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS ix_situation_tenant_status_occurred ON situation(tenant_id, status, occurred_at DESC);
CREATE INDEX IF NOT EXISTS ix_fact_situation_key_time ON situation_fact(situation_id, fact_key, observed_at DESC);
CREATE INDEX IF NOT EXISTS ix_task_assignee_status_due ON task(assignee_user_id, status, due_at);
CREATE INDEX IF NOT EXISTS ix_execution_situation_time_type ON execution_event(situation_id, occurred_at, event_type);
CREATE INDEX IF NOT EXISTS ix_audit_tenant_time ON audit_log(tenant_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS ix_notification_user_unread ON notification(user_id, read_at, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_outbox_due ON outbox_message(next_attempt_at) WHERE status IN ('PENDING','RETRY');
-- 설계 UK-outbox-idem: 재시도 가능한 전송의 중복 삽입을 DB에서 차단 (ADR-21).
CREATE UNIQUE INDEX IF NOT EXISTS uk_outbox_idem ON outbox_message(idempotency_key, channel);
CREATE UNIQUE INDEX IF NOT EXISTS uk_toc_node_version_key ON toc_node(toc_version_id, node_key);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sop_node_version_key ON sop_node(sop_version_id, node_key);
CREATE UNIQUE INDEX IF NOT EXISTS uk_plan_snapshot_version ON plan_context_snapshot(plan_id, version_no);
CREATE UNIQUE INDEX IF NOT EXISTS uk_situation_snapshot_version ON situation_snapshot(situation_id, version_no);
CREATE UNIQUE INDEX IF NOT EXISTS uk_document_revision_no ON document_revision(document_id, revision_no);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sop_version_no ON sop_version(sop_id, version_no);
CREATE UNIQUE INDEX IF NOT EXISTS uk_job_idempotency ON generation_job(tenant_id, idempotency_key) WHERE idempotency_key IS NOT NULL;

-- JSONB GIN indexes. Activate after EXPLAIN ANALYZE confirms query value.
CREATE INDEX IF NOT EXISTS ix_context_snapshot_json ON plan_context_snapshot USING gin(context_json jsonb_path_ops);
CREATE INDEX IF NOT EXISTS ix_fact_value_json ON situation_fact USING gin(value_json jsonb_path_ops);
CREATE INDEX IF NOT EXISTS ix_execution_payload_json ON execution_event USING gin(payload_json jsonb_path_ops);
